Rails.application.routes.draw do
  # Remove these autogenerated routes (they duplicate real routes and can confuse reviewers)
  # get "volunteers/new"
  # get "volunteers/create"
  # get "volunteers/show"
  # get "volunteers/edit"
  # get "volunteers/update"
  # get "volunteers/destroy"
  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"

  root "sessions#new"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  get  "/signup", to: "volunteers#new"
  post "/signup", to: "volunteers#create"

  resources :volunteers, except: [ :new, :create ]
  resources :events

  # Existing signup route (works)
  post "/events/:id/signup", to: "volunteers#signup_for_event", as: :signup_event

  # Admin routes (placeholder for Person 3)--------------------------------
  # get "/admin", to: "admin#dashboard"
  get "/admin", to: "admins#dashboard", as: :admin

  # editing profile
  get "/admin/profile/edit", to: "admins#edit_profile",   as: :edit_admin_profile
  patch "/admin/profile",     to: "admins#update_profile", as: :admin_profile
  # admin volunteer and event routes
  namespace :admin_area do
    get "analytics", to: "analytics#index", as: :analytics

    resources :volunteers
    resources :events
    resources :volunteer_assignments do
      member do
        patch :approve
        patch :reject
        patch :mark_completed
        patch :log_hours
      end
    end
  end

  # Add these for "My Events" + Withdraw (Person 2)
  resources :volunteer_assignments, only: [:index, :destroy]
end
