Rails.application.routes.draw do
  # Remove these autogenerated routes (they duplicate real routes and can confuse reviewers)
  # get "volunteers/new"
  # get "volunteers/create"
  # get "volunteers/show"
  # get "volunteers/edit"
  # get "volunteers/update"
  # get "volunteers/destroy"
  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"

  root "sessions#new"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  get  "/signup", to: "volunteers#new"
  post "/signup", to: "volunteers#create"

  resources :volunteers, except: [:new, :create]
  resources :events

  # Existing signup route (works)
  post "/events/:id/signup", to: "volunteers#signup_for_event", as: :signup_event

  # Add these for "My Events" + Withdraw (Person 2)
  resources :volunteer_assignments, only: [:index, :destroy]

  get "/admin", to: "admin#dashboard", as: :admin
end
